# -*- coding: utf-8 -*-
"""Project_Test.ipynb

Automatically generated by Colaboratory.
"""

!pip install face_recognition

!wget -c http://www.gstatic.com/tv/thumb/persons/487578/487578_v9_ba.jpg 
!wget -c https://www.biography.com/.image/t_share/MTE4MDAzNDEwNzg5ODI4MTEw/barack-obama-12782369-1-402.jpg
!wget -c https://api.time.com/wp-content/uploads/2017/12/barack-obama.jpeg

!mv 487578_v9_ba.jpg 1.jpg
!mv barack-obama-12782369-1-402.jpg 2.jpg
!mv barack-obama.jpeg 3.jpg

import face_recognition as f

kimg1 = f.load_image_file("1.jpg")
kimg2 = f.load_image_file("2.jpg")
uimg1 = f.load_image_file("3.jpg")

try :
  kimg1_e = f.face_encodings(kimg1)[0]
  kimg2_e = f.face_encodings(kimg2)[0]
  uimg1_e = f.face_encodings(uimg1)[0]
except IndexError :
  print("One of the faces did not get encoded")
  quit()

known_faces = [kimg1_e,kimg2_e]
results = f.compare_faces(known_faces, uimg1_e)

print("Image matches face 1? :" , results[0])
print("Image matches face 2? :" , results[1])